apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: psbadge-svc-autoscaler
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: psbadge-svc
  minReplicas: 1
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70